[package]
name = "rzarrs"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib", "lib"]

[dependencies]
savvy = { version = "0.10.2", default-features = false, features = ["complex"] }
zarrs = { version = "0.23", default-features = false, features = [
    "filesystem",
    "async",
    "ndarray",
    "gzip",
    "zstd",
    "sharding",
    "transpose",
    "crc32c",
] }
zarrs_zip = { version = "0.5.1", optional = true }
rc-zip = { version = "5.4.1", optional = true, features = ["deflate"] }
zarrs_object_store = { version = "0.6", default-features = false }
url = "2"
tokio = { version = "1", default-features = false, features = ["rt", "time"] }
serde_json = "1"
dashu-int = "0.4.2"
dashu-float = "0.4.4"
half = "2.7"
num-complex = "0.4.3"

[features]
default = ["aws", "zip", "fs", "blosc"]
http = ["zarrs_object_store/http"]
aws = ["http", "zarrs_object_store/aws"]
gcp = ["http", "zarrs_object_store/gcp"]
azure = ["http", "zarrs_object_store/azure"]
fs = ["zarrs_object_store/fs"]
cloud = ["aws", "gcp", "azure"]
zip = ["dep:zarrs_zip", "dep:rc-zip"]
blosc = ["zarrs/blosc"]
altrep = ["savvy/altrep"]
async-altrep = ["altrep", "tokio/rt-multi-thread", "tokio/sync"]
simd-cast = []

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
