# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib Rzarrs, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}

# Prohibit modifying environments

#' @export
`$<-.savvy_Rzarrs__sealed` <- function(x, name, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' @export
`[[<-.savvy_Rzarrs__sealed` <- function(x, i, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}


`rzarrs_int64_is_na` <- function(`x`) {
  .Call(savvy_rzarrs_int64_is_na__impl, `x`)
}


`rzarrs_int64_math` <- function(`x`, `op`) {
  .Call(savvy_rzarrs_int64_math__impl, `x`, `op`)
}


`rzarrs_int64_op` <- function(`x`, `y`, `op`) {
  .Call(savvy_rzarrs_int64_op__impl, `x`, `y`, `op`)
}


`rzarrs_int64_summary` <- function(`x`, `op`, `_na_rm`) {
  .Call(savvy_rzarrs_int64_summary__impl, `x`, `op`, `_na_rm`)
}


`rzarrs_int64_to_double` <- function(`x`) {
  .Call(savvy_rzarrs_int64_to_double__impl, `x`)
}


`rzarrs_int64_values` <- function(`x`) {
  .Call(savvy_rzarrs_int64_values__impl, `x`)
}


`rzarrs_uint64_is_na` <- function(`x`) {
  .Call(savvy_rzarrs_uint64_is_na__impl, `x`)
}


`rzarrs_uint64_math` <- function(`x`, `op`) {
  .Call(savvy_rzarrs_uint64_math__impl, `x`, `op`)
}


`rzarrs_uint64_op` <- function(`x`, `y`, `op`) {
  .Call(savvy_rzarrs_uint64_op__impl, `x`, `y`, `op`)
}


`rzarrs_uint64_summary` <- function(`x`, `op`, `_na_rm`) {
  .Call(savvy_rzarrs_uint64_summary__impl, `x`, `op`, `_na_rm`)
}


`rzarrs_uint64_to_double` <- function(`x`) {
  .Call(savvy_rzarrs_uint64_to_double__impl, `x`)
}


`rzarrs_uint64_values` <- function(`x`) {
  .Call(savvy_rzarrs_uint64_values__impl, `x`)
}

### wrapper functions for ZarrArray

`ZarrArray_chunk_shape` <- function(self) {
  function() {
    .Call(savvy_ZarrArray_chunk_shape__impl, `self`)
  }
}

`ZarrArray_dimension_names` <- function(self) {
  function() {
    .Call(savvy_ZarrArray_dimension_names__impl, `self`)
  }
}

`ZarrArray_dtype` <- function(self) {
  function() {
    .Call(savvy_ZarrArray_dtype__impl, `self`)
  }
}

`ZarrArray_dtype_plan` <- function(self) {
  function() {
    .Call(savvy_ZarrArray_dtype_plan__impl, `self`)
  }
}

`ZarrArray_metadata` <- function(self) {
  function() {
    .Call(savvy_ZarrArray_metadata__impl, `self`)
  }
}

`ZarrArray_metadata_json` <- function(self) {
  function() {
    .Call(savvy_ZarrArray_metadata_json__impl, `self`)
  }
}

`ZarrArray_ndim` <- function(self) {
  function() {
    .Call(savvy_ZarrArray_ndim__impl, `self`)
  }
}

`ZarrArray_retrieve` <- function(self) {
  function(`starts`, `ends`) {
    .Call(savvy_ZarrArray_retrieve__impl, `self`, `starts`, `ends`)
  }
}

`ZarrArray_shape` <- function(self) {
  function() {
    .Call(savvy_ZarrArray_shape__impl, `self`)
  }
}

`.savvy_wrap_ZarrArray` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`chunk_shape` <- `ZarrArray_chunk_shape`(ptr)
  e$`dimension_names` <- `ZarrArray_dimension_names`(ptr)
  e$`dtype` <- `ZarrArray_dtype`(ptr)
  e$`dtype_plan` <- `ZarrArray_dtype_plan`(ptr)
  e$`metadata` <- `ZarrArray_metadata`(ptr)
  e$`metadata_json` <- `ZarrArray_metadata_json`(ptr)
  e$`ndim` <- `ZarrArray_ndim`(ptr)
  e$`retrieve` <- `ZarrArray_retrieve`(ptr)
  e$`shape` <- `ZarrArray_shape`(ptr)

  class(e) <- c("Rzarrs::ZarrArray", "ZarrArray", "savvy_Rzarrs__sealed")
  e
}


#' A handle to a Zarr array within a store.
#'
#' @export
`ZarrArray` <- new.env(parent = emptyenv())

### associated functions for ZarrArray

`ZarrArray`$`open` <- function(`store`, `path`) {
  `store` <- .savvy_extract_ptr(`store`, "Rzarrs::ZarrStore")
  .savvy_wrap_ZarrArray(.Call(savvy_ZarrArray_open__impl, `store`, `path`))
}

`ZarrArray`$`open_object_store` <- function(`store`, `path`) {
  `store` <- .savvy_extract_ptr(`store`, "Rzarrs::ZarrObjectStore")
  .savvy_wrap_ZarrArray(.Call(savvy_ZarrArray_open_object_store__impl, `store`, `path`))
}


class(`ZarrArray`) <- c("Rzarrs::ZarrArray__bundle", "savvy_Rzarrs__sealed")

#' @export
`print.Rzarrs::ZarrArray__bundle` <- function(x, ...) {
  cat('Rzarrs::ZarrArray\n')
}

### wrapper functions for ZarrGroup

`ZarrGroup_attributes` <- function(self) {
  function() {
    .Call(savvy_ZarrGroup_attributes__impl, `self`)
  }
}

`ZarrGroup_attributes_json` <- function(self) {
  function() {
    .Call(savvy_ZarrGroup_attributes_json__impl, `self`)
  }
}

`ZarrGroup_children` <- function(self) {
  function(`recursive`) {
    .Call(savvy_ZarrGroup_children__impl, `self`, `recursive`)
  }
}

`.savvy_wrap_ZarrGroup` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`attributes` <- `ZarrGroup_attributes`(ptr)
  e$`attributes_json` <- `ZarrGroup_attributes_json`(ptr)
  e$`children` <- `ZarrGroup_children`(ptr)

  class(e) <- c("Rzarrs::ZarrGroup", "ZarrGroup", "savvy_Rzarrs__sealed")
  e
}


#' A handle to a Zarr group (root or sub-group) within a store.
#'
#' Groups may contain arrays and/or sub-groups.  Use `$attributes()` to read
#' the group's JSON attributes as a native R list, and `$children()` to list
#' the immediate child nodes.
#'
#' @export
`ZarrGroup` <- new.env(parent = emptyenv())

### associated functions for ZarrGroup

`ZarrGroup`$`open` <- function(`store`, `path`) {
  `store` <- .savvy_extract_ptr(`store`, "Rzarrs::ZarrStore")
  .savvy_wrap_ZarrGroup(.Call(savvy_ZarrGroup_open__impl, `store`, `path`))
}

`ZarrGroup`$`open_object_store` <- function(`store`, `path`) {
  `store` <- .savvy_extract_ptr(`store`, "Rzarrs::ZarrObjectStore")
  .savvy_wrap_ZarrGroup(.Call(savvy_ZarrGroup_open_object_store__impl, `store`, `path`))
}


class(`ZarrGroup`) <- c("Rzarrs::ZarrGroup__bundle", "savvy_Rzarrs__sealed")

#' @export
`print.Rzarrs::ZarrGroup__bundle` <- function(x, ...) {
  cat('Rzarrs::ZarrGroup\n')
}

### wrapper functions for ZarrObjectStore

`ZarrObjectStore_url` <- function(self) {
  function() {
    .Call(savvy_ZarrObjectStore_url__impl, `self`)
  }
}

`.savvy_wrap_ZarrObjectStore` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`url` <- `ZarrObjectStore_url`(ptr)

  class(e) <- c("Rzarrs::ZarrObjectStore", "ZarrObjectStore", "savvy_Rzarrs__sealed")
  e
}


#' A handle to an object-store Zarr backend (S3, GCS, Azure, …).
#'
#' Credentials are discovered from the standard environment variables for each
#' provider — the same variables used by the AWS CLI, `gsutil`, `azcopy`, etc.
#' No credentials need to be passed to R; set them in the process environment
#' before calling `ZarrObjectStore$open()`.
#'
#' @export
`ZarrObjectStore` <- new.env(parent = emptyenv())

### associated functions for ZarrObjectStore

`ZarrObjectStore`$`open` <- function(`url`) {
  .savvy_wrap_ZarrObjectStore(.Call(savvy_ZarrObjectStore_open__impl, `url`))
}


class(`ZarrObjectStore`) <- c("Rzarrs::ZarrObjectStore__bundle", "savvy_Rzarrs__sealed")

#' @export
`print.Rzarrs::ZarrObjectStore__bundle` <- function(x, ...) {
  cat('Rzarrs::ZarrObjectStore\n')
}

### wrapper functions for ZarrStore

`ZarrStore_path` <- function(self) {
  function() {
    .Call(savvy_ZarrStore_path__impl, `self`)
  }
}

`.savvy_wrap_ZarrStore` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`path` <- `ZarrStore_path`(ptr)

  class(e) <- c("Rzarrs::ZarrStore", "ZarrStore", "savvy_Rzarrs__sealed")
  e
}


#' A handle to a local Zarr filesystem store.
#'
#' @export
`ZarrStore` <- new.env(parent = emptyenv())

### associated functions for ZarrStore

`ZarrStore`$`open` <- function(`path`) {
  .savvy_wrap_ZarrStore(.Call(savvy_ZarrStore_open__impl, `path`))
}


class(`ZarrStore`) <- c("Rzarrs::ZarrStore__bundle", "savvy_Rzarrs__sealed")

#' @export
`print.Rzarrs::ZarrStore__bundle` <- function(x, ...) {
  cat('Rzarrs::ZarrStore\n')
}

### wrapper functions for ZarrVcf

`ZarrVcf_call` <- function(self) {
  function(`name`) {
    .Call(savvy_ZarrVcf_call__impl, `self`, `name`)
  }
}

`ZarrVcf_call_genotype_phased` <- function(self) {
  function(`variants` = NULL, `samples` = NULL) {
    .Call(savvy_ZarrVcf_call_genotype_phased__impl, `self`, `variants`, `samples`)
  }
}

`ZarrVcf_contigs` <- function(self) {
  function() {
    .Call(savvy_ZarrVcf_contigs__impl, `self`)
  }
}

`ZarrVcf_fields` <- function(self) {
  function() {
    .Call(savvy_ZarrVcf_fields__impl, `self`)
  }
}

`ZarrVcf_filters` <- function(self) {
  function() {
    .Call(savvy_ZarrVcf_filters__impl, `self`)
  }
}

`ZarrVcf_genotypes` <- function(self) {
  function(`variants` = NULL, `samples` = NULL) {
    .Call(savvy_ZarrVcf_genotypes__impl, `self`, `variants`, `samples`)
  }
}

`ZarrVcf_n_samples` <- function(self) {
  function() {
    .Call(savvy_ZarrVcf_n_samples__impl, `self`)
  }
}

`ZarrVcf_n_variants` <- function(self) {
  function() {
    .Call(savvy_ZarrVcf_n_variants__impl, `self`)
  }
}

`ZarrVcf_samples` <- function(self) {
  function() {
    .Call(savvy_ZarrVcf_samples__impl, `self`)
  }
}

`ZarrVcf_variant` <- function(self) {
  function(`name`) {
    .Call(savvy_ZarrVcf_variant__impl, `self`, `name`)
  }
}

`ZarrVcf_variant_allele` <- function(self) {
  function() {
    .Call(savvy_ZarrVcf_variant_allele__impl, `self`)
  }
}

`ZarrVcf_variant_contig` <- function(self) {
  function() {
    .Call(savvy_ZarrVcf_variant_contig__impl, `self`)
  }
}

`ZarrVcf_variant_position` <- function(self) {
  function() {
    .Call(savvy_ZarrVcf_variant_position__impl, `self`)
  }
}

`ZarrVcf_version` <- function(self) {
  function() {
    .Call(savvy_ZarrVcf_version__impl, `self`)
  }
}

`.savvy_wrap_ZarrVcf` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`call` <- `ZarrVcf_call`(ptr)
  e$`call_genotype_phased` <- `ZarrVcf_call_genotype_phased`(ptr)
  e$`contigs` <- `ZarrVcf_contigs`(ptr)
  e$`fields` <- `ZarrVcf_fields`(ptr)
  e$`filters` <- `ZarrVcf_filters`(ptr)
  e$`genotypes` <- `ZarrVcf_genotypes`(ptr)
  e$`n_samples` <- `ZarrVcf_n_samples`(ptr)
  e$`n_variants` <- `ZarrVcf_n_variants`(ptr)
  e$`samples` <- `ZarrVcf_samples`(ptr)
  e$`variant` <- `ZarrVcf_variant`(ptr)
  e$`variant_allele` <- `ZarrVcf_variant_allele`(ptr)
  e$`variant_contig` <- `ZarrVcf_variant_contig`(ptr)
  e$`variant_position` <- `ZarrVcf_variant_position`(ptr)
  e$`version` <- `ZarrVcf_version`(ptr)

  class(e) <- c("Rzarrs::ZarrVcf", "ZarrVcf", "savvy_Rzarrs__sealed")
  e
}


#' High-level VCF Zarr reader
#'
#' `ZarrVcf$open(x)` opens a VCF Zarr store (spec versions 0.1–0.4) and
#' returns an instance with methods to access variant, sample, and genotype data.
#'
#' @section Methods:
#' \describe{
#'   \item{`$open(x)`}{Open a VCF Zarr store from a path, URL, `ZarrStore`, or `ZarrObjectStore`.}
#'   \item{`$version()`}{VCF Zarr spec version string.}
#'   \item{`$n_variants()`, `$n_samples()`}{Number of variants and samples.}
#'   \item{`$samples()`, `$contigs()`, `$filters()`}{Character vectors of sample IDs, contig names, filter IDs.}
#'   \item{`$fields()`}{Available array names.}
#'   \item{`$variant_position()`, `$variant_contig()`, `$variant_allele()`}{Per-variant data.}
#'   \item{`$genotypes(variants, samples)`}{3-D array (variants × samples × ploidy) of integer genotypes.}
#'   \item{`$call_genotype_phased(variants, samples)`}{Boolean phased matrix.}
#'   \item{`$variant(name)`, `$call(name)`}{Generic accessor for `variant_<name>` / `call_<name>` arrays.}
#' }
#'
#' @export
`ZarrVcf` <- new.env(parent = emptyenv())

### associated functions for ZarrVcf

`ZarrVcf`$`open` <- function(`path`) {
  .savvy_wrap_ZarrVcf(.Call(savvy_ZarrVcf_open__impl, `path`))
}

`ZarrVcf`$`open_object_store` <- function(`url`) {
  .savvy_wrap_ZarrVcf(.Call(savvy_ZarrVcf_open_object_store__impl, `url`))
}

`ZarrVcf`$`open_store` <- function(`store`) {
  `store` <- .savvy_extract_ptr(`store`, "Rzarrs::ZarrStore")
  .savvy_wrap_ZarrVcf(.Call(savvy_ZarrVcf_open_store__impl, `store`))
}


class(`ZarrVcf`) <- c("Rzarrs::ZarrVcf__bundle", "savvy_Rzarrs__sealed")

#' @export
`print.Rzarrs::ZarrVcf__bundle` <- function(x, ...) {
  cat('Rzarrs::ZarrVcf\n')
}

