# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib Rzarrs, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}

# Prohibit modifying environments

#' @export
`$<-.savvy_Rzarrs__sealed` <- function(x, name, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' @export
`[[<-.savvy_Rzarrs__sealed` <- function(x, i, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}


### wrapper functions for ZarrArray

`ZarrArray_chunk_shape` <- function(self) {
  function() {
    .Call(savvy_ZarrArray_chunk_shape__impl, `self`)
  }
}

`ZarrArray_dimension_names` <- function(self) {
  function() {
    .Call(savvy_ZarrArray_dimension_names__impl, `self`)
  }
}

`ZarrArray_dtype` <- function(self) {
  function() {
    .Call(savvy_ZarrArray_dtype__impl, `self`)
  }
}

`ZarrArray_metadata_json` <- function(self) {
  function() {
    .Call(savvy_ZarrArray_metadata_json__impl, `self`)
  }
}

`ZarrArray_ndim` <- function(self) {
  function() {
    .Call(savvy_ZarrArray_ndim__impl, `self`)
  }
}

`ZarrArray_retrieve` <- function(self) {
  function(`starts`, `ends`) {
    .Call(savvy_ZarrArray_retrieve__impl, `self`, `starts`, `ends`)
  }
}

`ZarrArray_shape` <- function(self) {
  function() {
    .Call(savvy_ZarrArray_shape__impl, `self`)
  }
}

`.savvy_wrap_ZarrArray` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`chunk_shape` <- `ZarrArray_chunk_shape`(ptr)
  e$`dimension_names` <- `ZarrArray_dimension_names`(ptr)
  e$`dtype` <- `ZarrArray_dtype`(ptr)
  e$`metadata_json` <- `ZarrArray_metadata_json`(ptr)
  e$`ndim` <- `ZarrArray_ndim`(ptr)
  e$`retrieve` <- `ZarrArray_retrieve`(ptr)
  e$`shape` <- `ZarrArray_shape`(ptr)

  class(e) <- c("Rzarrs::ZarrArray", "ZarrArray", "savvy_Rzarrs__sealed")
  e
}


#' A handle to a Zarr array within a store.
#'
#' @export
`ZarrArray` <- new.env(parent = emptyenv())

### associated functions for ZarrArray

`ZarrArray`$`open` <- function(`store`, `path`) {
  `store` <- .savvy_extract_ptr(`store`, "Rzarrs::ZarrStore")
  .savvy_wrap_ZarrArray(.Call(savvy_ZarrArray_open__impl, `store`, `path`))
}


class(`ZarrArray`) <- c("Rzarrs::ZarrArray__bundle", "savvy_Rzarrs__sealed")

#' @export
`print.Rzarrs::ZarrArray__bundle` <- function(x, ...) {
  cat('Rzarrs::ZarrArray\n')
}

### wrapper functions for ZarrStore

`ZarrStore_path` <- function(self) {
  function() {
    .Call(savvy_ZarrStore_path__impl, `self`)
  }
}

`.savvy_wrap_ZarrStore` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`path` <- `ZarrStore_path`(ptr)

  class(e) <- c("Rzarrs::ZarrStore", "ZarrStore", "savvy_Rzarrs__sealed")
  e
}


#' A handle to a local Zarr filesystem store.
#'
#' @export
`ZarrStore` <- new.env(parent = emptyenv())

### associated functions for ZarrStore

`ZarrStore`$`open` <- function(`path`) {
  .savvy_wrap_ZarrStore(.Call(savvy_ZarrStore_open__impl, `path`))
}


class(`ZarrStore`) <- c("Rzarrs::ZarrStore__bundle", "savvy_Rzarrs__sealed")

#' @export
`print.Rzarrs::ZarrStore__bundle` <- function(x, ...) {
  cat('Rzarrs::ZarrStore\n')
}

